### PR TITLE
Backport glfwPostEmptyEvent from GLFW 3.1

### PR DESCRIPTION
**Pull request by pcwalton**
Backport from GLFW 3.1, with a bug relating to autorelease pools fixed.

This is needed for Servo off-main-thread compositing to work right. You can't poke the main event loop from another thread any other way, and if you can't kick the main loop awake from another thread the browser is just broken.

### CODE REVIEW

**Comment by metajack** [comment]
Did you submit the bugfix upstream as well?

**Comment by pcwalton** [comment]
I have not. Will do that in just a sec.

**Comment by pcwalton** [comment]
@metajack https://github.com/glfw/glfw/pull/372

**Comment by larsbergstrom** [comment]
I see that upstream landed. Should this PR be rebased on top of picking up the change from upstream?

**Comment by pcwalton** [comment]
Yeah, I'll do that.

**Comment by banthar** [comment]
I think merging 01743e7609f305e4c960d39f0673d1171b3ff1f4 broke compilation on linux:

```
/home/piotr/.cargo/git/checkouts/glfw-4fd4342c6777c12d/cargo-3.0.4/src/x11_window.c: In function ‘_glfwPlatformPostEmptyEvent’:
/home/piotr/.cargo/git/checkouts/glfw-4fd4342c6777c12d/cargo-3.0.4/src/x11_window.c:1206:43: error: ‘_GLFWlibraryX11’ has no member named ‘_NULL’
 event.xclient.message_type = _glfw.x11._NULL;
```

It looks like you need to to also merge 98552f1d75ac04fa5dd07e6b23bd43cd5045a4e1 which introduces this field.

**Pull request merged**
