### PR TITLE
Add metadata in preparation for crates.io

### PR DESCRIPTION
**Pull request by brendanzab**
cc. bjz/glfw-rs#252

### CODE REVIEW

**Comment by brendanzab** [comment]
We still need a build script - not sure if that will prevent publishing on crates.io:

```
warning: an arbitrary build command has now been deprecated.
         It has been replaced by custom build scripts.
         For more information, see http://doc.crates.io/build-script.html
```

**Comment by brendanzab** [comment]
Bump? Could anyone merge? I would like to get this on crates.io

**Comment by brendanzab** [comment]
If not I will make my own fork and publish that.

**Comment by jdm** [comment]
I don't understand why we want the Servo one on crates.io in particular?

**Comment by brendanzab** [comment]
We need it because you can't publish grates with git dependencies to crates.io

**Comment by brendanzab** [comment]
I guess I will just use my own fork then...

**Comment by jdm** [comment]
Is there a crate that depends on Servo's gflw fork? I feel like I'm missing context here.

**Comment by brendanzab** [comment]
Yes, [bjz/glfw-rs does](https://github.com/bjz/glfw-rs/blob/master/Cargo.toml#L33-L36).

**Comment by jdm** [comment]
Oh, I kept thinking this was servo's glfw-rs repository. Durrr.

**Comment by brendanzab** [comment]
Ok, we are now broken on the rust nightly by the lack of a build script. Can't make an issue due to us being on a fork >_<

**Pull request merged**
